services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: '1505'
      MYSQL_DATABASE: produtos_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mysql://root:1405@db:3306/produtos_db'
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  db_data:
